const LAUNDRY_REQUEST_SUCCESS = "LAUNDRY_REQUEST_SUCC";
const LAUNDRY_REQUEST_UPDATE = "LAUNDRY_REQUEST_UPDATE";
const LAUNDRY_REQUEST_DELETE = "LAUNDRY_REQUEST_DELETE";
const LAUNDRY_GET_REQUEST_SUCCESS = "LAUNDRY_GET_REQUEST_SUCC";
const LAUNDRY_GET_REQUEST_FAIL = "LAUNDRY_GET_REQUEST_FAIL";
const LAUNDRY_REQUEST_FAIL = "LAUNDRY_REQUEST_FAIL";
const LAUNDRY_REQUEST_CONFIRM = "LAUNDRY_REQUEST_ACCE";
const LAUNDRY_GET_PRICE = "LAUNDRY_GET_PRICE";

export const LAUNDRY_REQUEST_UPDATE_STATUS = "LAUNDRY_REQUEST_UPDATE_STATUS";

export {
  LAUNDRY_REQUEST_SUCCESS,
  LAUNDRY_REQUEST_UPDATE,
  LAUNDRY_REQUEST_DELETE,
  LAUNDRY_REQUEST_FAIL,
  LAUNDRY_GET_REQUEST_SUCCESS,
  LAUNDRY_GET_REQUEST_FAIL,
  LAUNDRY_REQUEST_CONFIRM,
  LAUNDRY_GET_PRICE,

};
